pull_request_rules:
  - name: automatic merge
    actions:
      comment:
        message: Thank you for contriubting! Your pull request will be updated from main and then merged automatically (do not update manually, and be sure to [allow changes to be pushed to your fork](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)).
      merge:
        method: squash
        commit_message_template: |-
          {{ title }} (#{{ number }})
          {{ body }}
    conditions:
      - -title~=(WIP|wip)
      - -label~=(blocked|do-not-merge|no-squash|two-approvers)
      - -merged
      - -closed
      - "#approved-reviews-by>=1"
      - -approved-reviews-by~=author
      - "#changes-requested-reviews-by=0"
      - status-success=validate-pr
      - "#review-threads-unresolved=0"
      - status-success~=Build using Hugo
      - author!=dependabot[bot]
      - author!=dependabot-preview[bot]
  - name: automatic merge of Dependabot PRs
    actions:
      comment:
        message: Thanks Dependabot!
      merge:
        method: squash
        commit_message_template: |-
          {{ title }} (#{{ number }})
          {{ body }}
    conditions:
      - -title~=(WIP|wip)
      - -label~=(blocked|do-not-merge)
      - -merged
      - -closed
      - author=dependabot[bot]
      - status-success~=Build using Hugo
  - name: if fails conventional commits
    actions:
      comment:
        message: Title does not follow the guidelines of [Conventional Commits](https://www.conventionalcommits.org). Please adjust title before merge.
    conditions:
      - author!=dependabot[bot]
      - author!=dependabot-preview[bot]
      - status-failure=Semantic PRs Failed
      - -merged
      - -closed
