name: Feature Request
description: Request a new feature
labels: [feature-request, needs-triage]
body:
  - type: checkboxes
    id: general
    attributes:
      label: General Information
      options:
        - label: I may be able to implement this feature request
          required: false
        - label: This feature might incur a breaking change
          required: false
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Describe the feature you would like added in as much detail as you can. Make sure you explain how it'll enhance the project, user-experience or feature set.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: |
        Whenever relevant, describe how you would like the feature to be implemented. Include any documentation that can help understand your idea in very concrete ways, such as code examples that leverage your feature, captures of design diagrams, ...
    validations:
      required: true
  - type: input
    id: cdk-version
    attributes:
      label: CDK CLI Version
      description: Output of `cdk version`
    validations:
      required: false
  - type: input
    id: section
    attributes:
      label: Section
      description: Name of workshop section, if relevant
    validations:
      required: false
  - type: input
    id: browser
    attributes:
      label: Browser
      description: all | Chrome | Firefox | Safari | etc...
    validations:
      required: false
  - type: input
    id: language
    attributes:
      label: Language
      description: all | TypeScript | Python | etc...
    validations:
      required: false
  - type: textarea
    id: other
    attributes:
      label: Other information
      description: |
        e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, gitter, etc
    validations:
      required: false
