name: Synth Python sample code

on:
  pull_request:
    paths:
      - code/python/**

jobs:
  main-workshop:
    name: CDK synth main-workshop sample code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
          architecture: x64

      - name: Install Python modules
        working-directory: code/python/main-workshop
        run: python3 -m pip install -r requirements.txt

      - name: CDK synth
        working-directory: code/python/main-workshop
        run: npx cdk synth

  pipelines-workshop:
    name: CDK synth pipelines-workshop sample code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
          architecture: x64

      - name: Install Python modules
        working-directory: code/python/pipelines-workshop
        run: python3 -m pip install -r requirements.txt

      - name: CDK synth
        working-directory: code/python/pipelines-workshop
        run: npx cdk synth
