# Automated actions for PRs against the v2-main branch
name: Intake Actions for PRs
on:
  pull_request:
    types:
      - labeled
      - opened
      - ready_for_review
      - reopened
      - synchronize
      - unlabeled
      - unlocked

jobs:
  core-label:
    env:
      CORE_MEMBERS: eladb,RomainMuller,garnaat,nija-at,skinny85,rix0rrr,NGL321,Jerry-AWS,MrArnoldPalmer,NetaNir,iliapolo,njlynch,ericzbeard,ccfife,fulghum,pkandasamy91,SoManyHs,uttarasridhar
    if: contains(env.CORE_MEMBERS.split(','), github.event.pull_request.user.login)
    runs-on: ubuntu-latest
    steps:
    - uses: andymckay/labeler@1.0.2
      with:
        add-labels: "core-contributor"
        ignore-if-labeled: true
        github-token: "${{ secrets.GITHUB_TOKEN }}"
  pr-checklist:
    steps:
    - uses: peter-evans/create-or-update-comment@v1
      with:
        body: |
            ### Pull Request Checklist
            * [ ] Testing
            - Unit test added (prefer not to modify an existing test, otherwise, it's probably a breaking change)
            * [ ] Title and Description
            - __Change type__: title prefixed with **fix**, **feat** and module name in parens, which will appear in changelog
            - __Title__: use lower-case and doesn't end with a period
            - __Breaking?__: last paragraph: 'BREAKING CHANGE: <describe what changed + link for details>'
            - __Issues__: Indicate issues fixed via: '**Fixes #xxx**' or '**Closes #xxx**'
